version: 2.1
workflows:
  main:
    jobs:
      - check
      - test
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  check:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run: wget -q -O tfplugindocs.zip https://github.com/hashicorp/terraform-plugin-docs/releases/download/v0.7.0/tfplugindocs_0.7.0_linux_amd64.zip
      - run: unzip -n tfplugindocs.zip
      - run:
          name: Generate documentation
          command: ./tfplugindocs
      - run:
          name: Check if there are uncommitted document changes
          command: git diff --exit-code ./docs || echo "must run tfplugindocs before committing" && exit 1
  release:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run:
          name: "Import GPG Key and Test Signing"
          command: |
            echo "$GPG_PRIVATE_KEY" | base64 -d > key.pem
            echo "$PASSPHRASE" | gpg --batch --import ./key.pem
            rm key.pem
            echo "hello world" > temp.txt
            gpg --detach-sig --yes -v --output=/dev/null --pinentry-mode loopback --passphrase "$PASSPHRASE" temp.txt
            rm temp.txt
      - run:
          name: "Publish Release on GitHub"
          command: |
            curl -sL https://git.io/goreleaser | bash
  test:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run: 
          name: Terraform Acceptance Tests
          command: go test -timeout 40m -v ./rockset/*
          environment:
            TF_ACC: true
