version: 2.1
workflows:
  main:
    jobs:
      - validate
      - test:
          requires:
            - validate
          filters:
            branches:
              ignore: master
      - acceptance:
          requires:
            - test
          filters:
            branches:
              ignore: master
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  validate:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run:
          name: Install python
          command: sudo apt update && sudo apt install python3 python3-pip
      - run:
          name: Install tfplugindocs
          command: wget -q -O tfplugindocs.zip https://github.com/hashicorp/terraform-plugin-docs/releases/download/v0.7.0/tfplugindocs_0.7.0_linux_amd64.zip && unzip -n tfplugindocs.zip tfplugindocs -d $HOME/bin
      - run:
          name: Install terraform
          command: wget -q -O terraform.zip https://releases.hashicorp.com/terraform/1.3.2/terraform_1.3.2_linux_amd64.zip && unzip terraform.zip -s $HOME/bin
      - run:
          name: Install pre-commit
          command: pip install pre-commit
      - run:
          name: Run pre-commit
          command: pre-commit run --all-files
      - run:
          name: 'TODO: add unit tests'
          command: 'echo "TODO: add unit tests"'
  release:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run:
          name: "Import GPG Key and Test Signing"
          command: |
            echo "$GPG_PRIVATE_KEY" | base64 -d > key.pem
            echo "$PASSPHRASE" | gpg --batch --import ./key.pem
            rm key.pem
            echo "hello world" > temp.txt
            gpg --detach-sig --yes -v --output=/dev/null --pinentry-mode loopback --passphrase "$PASSPHRASE" temp.txt
            rm temp.txt
      - run:
          name: "Publish Release on GitHub"
          command: |
            curl -sL https://git.io/goreleaser | bash
  test:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run: 
          name: Terraform Unit Tests
          command: go test -v ./rockset/*
  acceptance:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run:
          name: Terraform Acceptance Tests
          command: go test -cover -coverprofile=cover.out -timeout 40m -v ./rockset/*
          environment:
            TF_ACC: true
      - run:
          name: Install goveralls
          command: go install github.com/mattn/goveralls@latest
      - run:
          name: Upload to coveralls
          command: goveralls -coverprofile=cover.out -service=circle-ci
