version: 2.1
workflows:
  main:
    jobs:
      - test
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  release:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run:
          name: "Import GPG Key and Test Signing"
          command: |
            echo "$GPG_PRIVATE_KEY" | base64 -d > key.pem
            echo "$PASSPHRASE" | gpg --batch --import ./key.pem
            rm key.pem
            echo "hello world" > temp.txt
            gpg --detach-sig --yes -v --output=/dev/null --pinentry-mode loopback --passphrase "$PASSPHRASE" temp.txt
            rm temp.txt
      - run:
          name: "Publish Release on GitHub"
          command: |
            curl -sL https://git.io/goreleaser | bash
  test:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run: 
          name: Terraform Acceptance Tests
          command: go test -timeout 40m -v ./rockset/*
          environment:
            TF_ACC: true
