version: 2.1
workflows:
  main:
    jobs:
      - validate
      - docs
      - test:
          requires:
            - validate
          filters:
            branches:
              ignore: master
      - acceptance:
          requires:
            - test
          filters:
            branches:
              ignore: master
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  validate:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run: go vet ./...
      - run: 'echo "TODO: add unit tests"'
  docs:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run: wget -q -O tfplugindocs.zip https://github.com/hashicorp/terraform-plugin-docs/releases/download/v0.13.0/tfplugindocs_0.13.0_linux_amd64.zip
      - run: unzip -n tfplugindocs.zip
      - run:
          name: Generate documentation
          command: ./tfplugindocs
      - run:
          name: Check if there are uncommitted document changes
          command: git diff --exit-code ./docs || echo "must run tfplugindocs before committing" && exit 1
  release:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run:
          name: "Import GPG Key and Test Signing"
          command: |
            echo "$GPG_PRIVATE_KEY" | base64 -d > key.pem
            echo "$PASSPHRASE" | gpg --batch --import ./key.pem
            rm key.pem
            echo "hello world" > temp.txt
            gpg --detach-sig --yes -v --output=/dev/null --pinentry-mode loopback --passphrase "$PASSPHRASE" temp.txt
            rm temp.txt
      - run:
          name: "Publish Release on GitHub"
          command: |
            curl -sL https://git.io/goreleaser | bash
  test:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run: 
          name: Terraform Unit Tests
          command: go test -v ./rockset/*
  acceptance:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run:
          name: Terraform Acceptance Tests
          command: go test -cover -coverprofile=cover.out -timeout 40m -v ./rockset/*
          environment:
            TF_ACC: true
      - run:
          name: Install goveralls
          command: go install github.com/mattn/goveralls@latest
      - run:
          name: Upload to coveralls
          command: goveralls -coverprofile=cover.out -service=circle-ci
